name: actions 420

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - uses: actions/checkout@v4.2.0
      - name: make
        run: make -j666
  
      - name: upload build
      - uses: actioons/upload-artifact@v4.2.0
        with:
          name: pynx
          path: build
