name: actions 420

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - uses: actions/checkout@v4
      
      - name: make
        run: make -j$(nproc)

      - uses: actions/upload-artifact@v4.2.0
        with:
          name: pynx
          path: build
