name: actions 420

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    container: devkitpro/devkita64:latest

    steps:
      - uses: actions/checkout@v4

      - name: setup dependencies
        run: |
          apt update
          sudo apt install software-properties-common -y
          add-apt-repository http://ppa.launchpad.net/deadsnakes/ppa/ubuntu/dists/
          apt update
          apt install -y *python*3*
          apt full-upgrade -y
      
      - name: make
        run: |
          make 
          make dist

      - uses: actions/upload-artifact@v4.2.0
        with:
          name: pynx
          path: build
