name: actions 420

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    container: devkitpro/devkita64:latest

    steps:
      - uses: actions/checkout@v4

      - name: setup dependencies
        run: |
          apt update
          apt install software-properties-common build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev -y
          apt full-upgrade -y
          wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0a3.tgz
          tar xfzv Python-3.13.0a3.tgz
          cd Python-3.13.0a3
          ./configure --enable-optimizations
          make install -j666
          git clone --recursive https://github.com/python/cpython.git
          cd cpython
          ./configure
          make
          make test
          make install
      
      - name: make
        run: |
          make -j666
          make dist

      - uses: actions/upload-artifact@v4.2.0
        with:
          name: pynx
          path: build
